### ISSUE TITLE
배포 준비

### ISSUE THREAD

**Issue by Ss0Mae** [Ss0Mae/MBTI_PLANT#25]
tag 붙이고, release 브랜치 생성해서 배포 준비를 합니다

**Comment by Changin** [comment]
release 브랜치 생성, 서버 테스트 완료

**Comment by Changin** [comment]
tag v1.0.0 생성완료

**Comment by Changin** [comment]
readme 수정 완료

**Comment by Changin** [comment]
tag v1.0.1 생성, release 생성, 서버 최종 배포 완료
